version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: address_book
    ports:
      - 8001:8001
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'address_book'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

    volumes:
      - .dbdata:/var/lib/mysql/

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
